# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitets2 <- function(xt, F, w, yt, g, Etype, Ttype, Stype, sf) {
    .Call('TStools_fitets2', PACKAGE = 'TStools', xt, F, w, yt, g, Etype, Ttype, Stype, sf)
}

forets2 <- function(xt, F, w, h, Ttype, Stype, sf) {
    .Call('TStools_forets2', PACKAGE = 'TStools', xt, F, w, h, Ttype, Stype, sf)
}

errorets2 <- function(xt, F, w, yt, h, Etype, Ttype, Stype, sf, trace) {
    .Call('TStools_errorets2', PACKAGE = 'TStools', xt, F, w, yt, h, Etype, Ttype, Stype, sf, trace)
}

optimizeets2 <- function(xt, F, w, yt, g, h, Etype, Ttype, Stype, sf, trace, CFt, normalizer) {
    .Call('TStools_optimizeets2', PACKAGE = 'TStools', xt, F, w, yt, g, h, Etype, Ttype, Stype, sf, trace, CFt, normalizer)
}

