# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fitterwrap <- function(matxt, matF, matw, yt, vecg, Etype, Ttype, Stype, seasfreq) {
    .Call('TStools_fitterwrap', PACKAGE = 'TStools', matxt, matF, matw, yt, vecg, Etype, Ttype, Stype, seasfreq)
}

forecasterwrap <- function(matxt, matF, matw, h, Ttype, Stype, seasfreq) {
    .Call('TStools_forecasterwrap', PACKAGE = 'TStools', matxt, matF, matw, h, Ttype, Stype, seasfreq)
}

errorerwrap <- function(matxt, matF, matw, yt, h, Etype, Ttype, Stype, seasfreq, trace) {
    .Call('TStools_errorerwrap', PACKAGE = 'TStools', matxt, matF, matw, yt, h, Etype, Ttype, Stype, seasfreq, trace)
}

optimizerwrap <- function(matxt, matF, matw, yt, vecg, h, Etype, Ttype, Stype, seasfreq, trace, CFt, normalizer) {
    .Call('TStools_optimizerwrap', PACKAGE = 'TStools', matxt, matF, matw, yt, vecg, h, Etype, Ttype, Stype, seasfreq, trace, CFt, normalizer)
}

costfunc <- function(matxt, matF, matw, yt, vecg, h, Etype, Ttype, Stype, seasfreq, trace, CFt, normalizer, bounds, phi, Theta) {
    .Call('TStools_costfunc', PACKAGE = 'TStools', matxt, matF, matw, yt, vecg, h, Etype, Ttype, Stype, seasfreq, trace, CFt, normalizer, bounds, phi, Theta)
}

